/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/1n8W12WmT8e
 */
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"

export function Landing() {
  return (
    <div key="1" className="min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center">
        <Link className="flex items-center justify-center" href="#">
          <Package2Icon className="h-6 w-6" />
          <span className="sr-only">Carwash Inc</span>
        </Link>
        <nav className="ml-auto flex gap-4 sm:gap-6">
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="/admin">
            Admin panel
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="/employee">
            Employee panel
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Features
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Pricing
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            About
          </Link>
          <Link className="text-sm font-medium hover:underline underline-offset-4" href="#">
            Contact
          </Link>
        </nav>
      </header>
      <main className="flex flex-col">
        <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48 flex flex-col items-center justify-center">
          <div className="container space-y-4 px-4 md:px-6">
            <div className="flex flex-col items-center justify-center space-y-2 text-center">
              <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">
                Streamline Your Car Wash Operations
              </h1>
              <p className="max-w-[800px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                The modern car wash software platform designed to simplify your workflow, delight your customers, and
                grow your business.
              </p>
            </div>
            <div className="mx-auto w-full max-w-sm space-y-2">
              <form className="flex space-x-2">
                <Input className="max-w-lg flex-1" placeholder="Enter your email" type="email" />
                <Button type="submit">Learn More</Button>
              </form>
            </div>
          </div>
        </section>
        <section className="w-full flex flex-col items-center justify-center py-12 md:py-24 lg:py-32">
          <div className="container grid items-center gap-6 px-4 md:px-6">
            <div className="space-y-2 flex flex-col items-center">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Features</h2>
              <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400 text-pretty ">
                Our car wash software is packed with features to make managing your operations a breeze.
              </p>
            </div>
            <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
              <div className="flex flex-col items-center space-y-2">
                <DatabaseIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Automated Billing</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Streamline your payment processing with automated billing and invoicing.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <BoxIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Inventory Management</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Keep track of your supplies with integrated inventory management.
                  </p>
                </div>
              </div>
              <div className="flex flex-col items-center space-y-2">
                <UsersIcon className="h-10 w-10" />
                <div className="space-y-2 text-center">
                  <h3 className="font-bold">Customer Management</h3>
                  <p className="text-sm text-gray-500 dark:text-gray-400">
                    Build customer loyalty with robust CRM tools to track visits and preferences.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800 flex flex-col items-center">
          <div className="container px-4 md:px-6 items-center">
            <div className="grid items-center gap-6 lg:grid-cols-[1fr_400px] lg:gap-12 xl:grid-cols-[1fr_550px]">
              <img
                alt="Image"
                className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full"
                height="310"
                src="/placeholder.svg"
                width="550"
              />
              <div className="flex flex-col justify-center space-y-4">
                <div className="space-y-2">
                  <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Trusted by Car Wash Owners</h2>
                  <p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                    The software has made managing my car wash a delight. I can focus on my customers while the system
                    takes care of the rest.
                  </p>
                </div>
                <div className="flex flex-col gap-2 min-[400px]:flex-row">
                  <Link
                    className="inline-flex h-10 items-center justify-center rounded-md bg-gray-900 px-8 text-sm font-medium text-gray-50 shadow transition-colors hover:bg-gray-900/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:bg-gray-50 dark:text-gray-900 dark:hover:bg-gray-50/90 dark:focus-visible:ring-gray-300"
                    href="#"
                  >
                    Contact Sales
                  </Link>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 border-t flex flex-col items-center">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
            <div className="flex flex-col">
              <div className="space-y-3">
                <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
                  Ready to Transform Your Car Wash?
                </h2>
                <p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
                  Let your team focus on shipping features instead of managing infrastructure with automated
                  CI/CD.
                </p>
              </div>
              <div className="mx-auto w-full max-w-sm space-y-2">
                <form className="flex flex-col gap-4 sm:gap-0">
                  <div className="flex flex-col items-start">
                    <Label htmlFor="name">Name</Label>
                    <Input
                      className="h-10 border-gray-200 shadow-sm dark:border-gray-800"
                      placeholder="Jhon"
                      type="text"
                    />
                  </div>
                  <div className="flex flex-col items-start">
                    <Label htmlFor="email">Email</Label>
                    <Input
                      className="h-10 col-start-2 border-gray-200 shadow-sm dark:border-gray-800"
                      placeholder="Example@example.com"
                      type="email"
                    />
                  </div>
                  <div className="flex flex-col items-start">
                    <Label htmlFor="phone">Phone</Label>
                    <Input
                      className="h-10 col-start-3 border-gray-200 shadow-sm dark:border-gray-800"
                      placeholder="xxx-xxxx-xxxx"
                      type="tel"
                    />
                  </div>
                  <div className="flex flex-col items-start">
                    <Label htmlFor="company">Company</Label>
                    <Input
                      className="h-10 border-gray-200 shadow-sm dark:border-gray-800"
                      placeholder="Jhon company"
                      type="text"
                    />
                  </div>
                  <Button className="h-10 col-start-3 sm:col-start-4" type="submit">
                    Request a Demo
                  </Button>
                </form>
              </div>
            </div>
          </div>
        </section>
        <footer className="flex flex-col gap-2 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
          <p className="text-xs text-gray-500 dark:text-gray-400">© 2024 Carwash Inc. All rights reserved.</p>
          <nav className="sm:ml-auto flex gap-4 sm:gap-6">
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Terms of Service
            </Link>
            <Link className="text-xs hover:underline underline-offset-4" href="#">
              Privacy
            </Link>
          </nav>
        </footer>
      </main >
    </div >
  )
}


function Package2Icon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function DatabaseIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <ellipse cx="12" cy="5" rx="9" ry="3" />
      <path d="M3 5V19A9 3 0 0 0 21 19V5" />
      <path d="M3 12A9 3 0 0 0 21 12" />
    </svg>
  )
}


function BoxIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>
  )
}


function UsersIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>
  )
}
